name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black
    
    - name: Run code quality checks
      run: |
        flake8 quant_option.py src/ --max-line-length=88 --ignore=E203,W503
        black --check quant_option.py src/
    
    - name: Run tests
      run: |
        PYTHONPATH=. pytest tests --maxfail=1 --disable-warnings -q -m "not slow"

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t quant-option .
    
    - name: Test Docker image
      run: |
        docker run --rm quant-option --help

  artifacts:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate artifacts
      run: |
        python scripts/run_hedge.py --S0 100 --K 100 --T 0.25 --r 0.01 --sigma 0.2 --n-paths 5000 --rebalance-every 1,2,5,10 --fee-bps 1.0
        python scripts/calibrate_surface.py
        python scripts/benchmark_performance.py
    
    - name: Upload plots
      uses: actions/upload-artifact@v4
      with:
        name: plots
        path: plots/**/*.png
    
    - name: Upload benchmarks
      uses: actions/upload-artifact@v4
      with:
        name: benchmarks
        path: benchmarks/** 